<a href="https://colab.research.google.com/github/andykhv/notebooks/blob/main/mnist_fashion_lenet5.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import torch
import torchvision
import torchvision.transforms as transforms

In [ ]:
test = [ [ [0,0,0], [1,1,1] ], [ [2,2,2], [3,3,3] ] ]
test = torch.tensor(test)
ones = torch.ones_like(test)
rands = torch.rand_like(test, dtype=torch.float)

print(test.shape)
print(ones)
print(rands)
print(test)

torch.Size([2, 2, 3])
tensor([[[1, 1, 1],
         [1, 1, 1]],

        [[1, 1, 1],
         [1, 1, 1]]])
tensor([[[0.4027, 0.5700, 0.3110],
         [0.4885, 0.4676, 0.1336]],

        [[0.6986, 0.9239, 0.7761],
         [0.5760, 0.2397, 0.6287]]])
tensor([[[0, 0, 0],
         [1, 1, 1]],

        [[2, 2, 2],
         [3, 3, 3]]])


In [ ]:
print(ones.device)
print(rands.device)
print(test.device)

cpu
cpu
cpu


In [ ]:
ones.shape

torch.Size([2, 2, 3])

In [ ]:
cat = torch.cat([ones, rands, test], dim=2)
print(cat)
print(cat.shape)

# [6,2,3]
# [ [[2, 2, 3], [1,1,1]], [[], []], [[], []], [[], []], [[], []], [[], []]]

# [2,6,3]
# [[[], [], [], [], [], []], [[], [], [], [], [], []]]

# [2,2,9]
# [ [ 1, 1, 1, ], [  ] ]

tensor([[[1.0000, 1.0000, 1.0000, 0.4027, 0.5700, 0.3110, 0.0000, 0.0000,
          0.0000],
         [1.0000, 1.0000, 1.0000, 0.4885, 0.4676, 0.1336, 1.0000, 1.0000,
          1.0000]],

        [[1.0000, 1.0000, 1.0000, 0.6986, 0.9239, 0.7761, 2.0000, 2.0000,
          2.0000],
         [1.0000, 1.0000, 1.0000, 0.5760, 0.2397, 0.6287, 3.0000, 3.0000,
          3.0000]]])
torch.Size([2, 2, 9])


In [ ]:
input = [1,1]
cat[input]

tensor([[[1.0000, 1.0000, 1.0000, 0.6986, 0.9239, 0.7761, 2.0000, 2.0000,
          2.0000],
         [1.0000, 1.0000, 1.0000, 0.5760, 0.2397, 0.6287, 3.0000, 3.0000,
          3.0000]],

        [[1.0000, 1.0000, 1.0000, 0.6986, 0.9239, 0.7761, 2.0000, 2.0000,
          2.0000],
         [1.0000, 1.0000, 1.0000, 0.5760, 0.2397, 0.6287, 3.0000, 3.0000,
          3.0000]]])

In [ ]:
x = torch.tensor([[1., -1.], [1., 1.]], requires_grad=True)
out = x.sum()
out.backward()
x.grad

x.view(4)

tensor([ 1., -1.,  1.,  1.], grad_fn=<ViewBackward0>)

In [ ]:
from torch.utils.tensorboard import SummaryWriter
from datetime import datetime

transform = transforms.Compose([transforms.ToTensor(), transforms.Normalize((0.5),(0.5))])

#create datasets
training_set = torchvision.datasets.FashionMNIST('./data', train=True, transform=transform, download=True)
validation_set = torchvision.datasets.FashionMNIST('./data', train=False, transform=transform, download=True)

100%|██████████| 26421880/26421880 [00:02<00:00, 12404594.79it/s]


Extracting ./data/FashionMNIST/raw/train-images-idx3-ubyte.gz to ./data/FashionMNIST/raw



100%|██████████| 29515/29515 [00:00<00:00, 209622.52it/s]


Extracting ./data/FashionMNIST/raw/train-labels-idx1-ubyte.gz to ./data/FashionMNIST/raw



100%|██████████| 4422102/4422102 [00:01<00:00, 3930863.96it/s]


Extracting ./data/FashionMNIST/raw/t10k-images-idx3-ubyte.gz to ./data/FashionMNIST/raw



100%|██████████| 5148/5148 [00:00<00:00, 19593717.78it/s]

Extracting ./data/FashionMNIST/raw/t10k-labels-idx1-ubyte.gz to ./data/FashionMNIST/raw



In [ ]:
print(training_set)

Dataset FashionMNIST
    Number of datapoints: 60000
    Root location: ./data
    Split: Train
    StandardTransform
Transform: Compose(
               ToTensor()
               Normalize(mean=0.5, std=0.5)
           )


In [ ]:
#create loaders
training_loader = torch.utils.data.DataLoader(training_set, shuffle=True, batch_size=4)
validation_loader = torch.utils.data.DataLoader(validation_set, shuffle=False, batch_size=4)

#class labels
classes = ('T-shirt/top', 'Trouser', 'Pullover', 'Dress', 'Coat',
        'Sandal', 'Shirt', 'Sneaker', 'Bag', 'Ankle Boot')

#Report split sizes
print('Training set has {} instances'.format(len(training_set)))
print('Validation set has {} instances'.format(len(validation_set)))

Training set has 60000 instances
Validation set has 10000 instances


In [ ]:
import matplotlib.pyplot as plt
import numpy as np

# Helper function for inline image display
def matplotlib_imshow(img, one_channel=False):
    if one_channel:
        img = img.mean(dim=0)
    img = img / 2 + 0.5     # unnormalize
    npimg = img.numpy()
    if one_channel:
        plt.imshow(npimg, cmap="Greys")
    else:
        plt.imshow(np.transpose(npimg, (1, 2, 0)))

In [ ]:
#training_iter = iter(training_loader)
#images, labels = next(training_iter)

#create grid from the images and show them
#img_grid = torchvision.utils.make_grid(images)
#matplotlib_imshow(img_grid, one_channel=True)
#print(' '.join(classes[labels[j]] for j in range(4)))

In [ ]:
import torch.nn as nn
import torch.nn.functional as F

class GarmentClassifier(nn.Module):
  def __init__(self):
    super(GarmentClassifier, self).__init__()
    self.conv1 = nn.Conv2d(in_channels=1, out_channels=6, kernel_size=5)
    self.pool = nn.MaxPool2d(kernel_size=2, stride=2)
    self.conv2 = nn.Conv2d(in_channels=6, out_channels=16, kernel_size=5)
    self.fc1 = nn.Linear(in_features=16 * 4 * 4, out_features=120)
    self.fc2 = nn.Linear(in_features=120, out_features=84)
    self.fc3 = nn.Linear(in_features=84, out_features=10)

  def forward(self, x):
    x = self.pool(F.relu(self.conv1(x)))
    x = self.pool(F.relu(self.conv2(x)))
    x = x.view(-1, 16 * 4 * 4)
    x = F.relu(self.fc1(x))
    x = F.relu(self.fc2(x))
    x = self.fc3(x)
    return x

model = GarmentClassifier()

In [ ]:
#loss functions expect data in batches, we will create batches of 4

loss_fn = torch.nn.CrossEntropyLoss()

#represents the model's confidence in each of the 10 classes for a given input
dummy_outputs = torch.rand(4, 10)
#represents the correct class among the 10 being tested
dummy_labels = torch.tensor([1,5,3,7])

print(dummy_outputs)
print(dummy_labels)

#loss = loss_fn(dummy_outputs, dummy_labels)
#print('Total loss for this batch: {}'.format(loss.item()))

tensor([[0.3768, 0.9489, 0.6123, 0.2639, 0.4472, 0.4284, 0.8145, 0.7718, 0.7461,
         0.0123],
        [0.2940, 0.1155, 0.7632, 0.6275, 0.0470, 0.9756, 0.3935, 0.4651, 0.5228,
         0.9260],
        [0.5804, 0.5233, 0.3657, 0.8335, 0.0576, 0.3730, 0.2103, 0.9246, 0.7134,
         0.4346],
        [0.4212, 0.1212, 0.9134, 0.9378, 0.5017, 0.1880, 0.1075, 0.5244, 0.4221,
         0.0489]])
tensor([1, 5, 3, 7])


In [ ]:
#Optimizers specified in the torch.optim package
optimizer = torch.optim.SGD(model.parameters(), lr=0.001, momentum=0.9)

In [ ]:
def train_one_epoch(epoch_index, tb_writer):
  running_loss = 0.
  last_loss = 0.

  for count, (inputs, labels) in enumerate(training_loader):
    optimizer.zero_grad() #zero gradients every batch
    outputs = model(inputs) #forward pass

    #compute loss and its gradients
    loss = loss_fn(outputs, labels)
    loss.backward()

    #adjust learning weights
    optimizer.step()

    #gather data and report
    running_loss += loss.item()
    if count % 1000 == 999:
      last_loss = running_loss / 1000 #loss per batch
      print('batch {}, loss: {}'.format(count + 1, last_loss))
      tb_x = epoch_index * len(training_loader) + count + 1
      tb_writer.add_scalar('Loss/train', last_loss, tb_x)
      running_loss = 0

  return last_loss

In [ ]:
timestamp = datetime.now().strftime('%Y%m%d_%H%M%S')
writer = SummaryWriter('runs/lenet5_maxpool_relu')
epoch_number = 0

EPOCHS = 5

best_vloss = 1_000_000.

for epoch in range(EPOCHS):
  print('EPOCH {}:'.format(epoch_number + 1))

  #gradient tracking on, do a pass over data
  model.train(True)
  avg_loss = train_one_epoch(epoch_number, writer)

  #set model to evaluation mode, disabling dropout and using population
  #statistics for batch normalization
  model.eval()

  #disable gradient computation and reduce memory consumption
  running_vloss = 0.0
  with torch.no_grad():
    for i, vdata in enumerate(validation_loader):
      vinputs, vlabels = vdata
      voutputs = model(vinputs)
      vloss = loss_fn(voutputs, vlabels)
      running_vloss += vloss

  avg_vloss = running_vloss / (i + 1)
  print('LOSS train {} valid {}'.format(avg_loss, avg_vloss))

  #log running loss averaged per batch for both training and validation
  writer.add_scalars('Training vs. Validation Loss',
                     { 'Training': avg_loss, 'Validation': avg_vloss},
                     epoch_number + 1)
  writer.flush()

  #track best performance, and save model's state
  if avg_vloss < best_vloss:
    best_vloss = avg_vloss
    model_path = 'model_{}_{}'.format(timestamp, epoch_number)
    torch.save(model.state_dict(), model_path)

  epoch_number += 1


EPOCH 1:
batch 1000, loss: 2.0500668913722038
batch 2000, loss: 0.8527674072533846
batch 3000, loss: 0.6661956694293767
batch 4000, loss: 0.6016246316577308
batch 5000, loss: 0.5593955060234294
batch 6000, loss: 0.5332814521880355
batch 7000, loss: 0.5079441717648878
batch 8000, loss: 0.507990576643264
batch 9000, loss: 0.474091516426357
batch 10000, loss: 0.43986326645582446
batch 11000, loss: 0.45774787388468396
batch 12000, loss: 0.4233336500849109
batch 13000, loss: 0.4066347028008895
batch 14000, loss: 0.42871725975826847
batch 15000, loss: 0.4005424371238259
LOSS train 0.4005424371238259 valid 0.42974355816841125
EPOCH 2:
batch 1000, loss: 0.3858801536022802
batch 2000, loss: 0.3610106304203946
batch 3000, loss: 0.37806677814817524
batch 4000, loss: 0.36983968287854807
batch 5000, loss: 0.3624696763869724
batch 6000, loss: 0.3615973337913747
batch 7000, loss: 0.36974083856516515
batch 8000, loss: 0.3673414829936519
batch 9000, loss: 0.36293719217198667
batch 10000, loss: 0.372750